### PR TITLE
Share TBA Urls via Intent

### LINKED ISSUE #689: Share TBA Links
From @tytremblay:

> Feature request: enable sharing of TBA links via the TBA Android app.

https://www.facebook.com/groups/moardata/permalink/1099497873403840/

### PR DESCRIPTION
**Pull request by phil-lopreiato**
device-2016-04-13-183828
Fixes #689

---
This change is [Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/692)

### CODE REVIEW

**Comment by nwalters512** [comment]
Nice and simple implementation, I like it.

I'm wondering though, does it really make sense to have a share button on say, the MyTBA page? Or the yearly event list? Or the generic gameday page? I could see wanting to send a link to an event or a team or a match, but the other ones seem kind of pointless.

**Comment by fangeugene** [comment]
I agree with Nathan. I think Event, Team, and Team@Event are all that we really need to support for now. Those also have nice links on the website.

**Comment by nwalters512** [comment]
Might as well throw in some tests to keep Coveralls happy.

**Comment by phil-lopreiato** [comment]
Fair enough! 

(also I disabled the coveralls comments, I find them obnoxious :P )

**Pull request merged**
