### PR TITLE
Update rxjava to v1.1.0

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Changelogs:
https://github.com/ReactiveX/RxAndroid/blob/master/CHANGES.md
https://github.com/ReactiveX/RxJava/releases

---
This change is [Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/676)

### CODE REVIEW

**Comment by nwalters512** [comment]
Does stuff break if you bump RxJava all the way to 1.1.2?

**Comment by phil-lopreiato** [comment]
I'm letting the current version of [RxAndroid](https://github.com/ReactiveX/RxAndroid/blob/master/CHANGES.md) dictate the target level, since they have to remain in-sync across modules.

**Comment by phil-lopreiato** [comment]
Tests failing with code 137 is a result of the robolectric out of memory bug, so not our problem (but still incredibly annoying)

**Comment by nwalters512** [comment]
RxAndroid recommends explicitly depending on the latest version of RxJava: https://github.com/ReactiveX/RxAndroid#binaries

**Comment by phil-lopreiato** [comment]
TIL. I'll update it then

**Pull request merged**
