### PR TITLE
Update okhttp to latest 3.2.0

### PR DESCRIPTION
**Pull request by nwalters512**
Should help with a few crashes we've been seeing in the Dev Console. And it's always good to be running the latest and greatest code?

---
This change is [Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/636)

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
IIRC, it's more complicated than that, because the package name changed. Might want to double check that (and check what version retrofit is depending on). I think this was also the blocker for updating to the newest retrofit

**Comment by nwalters512** [comment]
It looks like Retrofit now depends on `3.2.0`: [pom.xml](https://github.com/square/retrofit/blob/master/retrofit/pom.xml#L18).

Good catch with the package name though. Something is keeping around version `2.5.0` of OkHttp in the project, so the build succeeded just fine, but `3.2.0` isn't actually being used. So yeah, there's more work to be done on this.

**Comment by nwalters512** [comment]
I think that should be it. Most of the changes were simply changing the package in the imports. A few of the APIs changed a bit, but those were easy to update.

The app builds, installs, and runs properly with the new library versions.

**Comment by phil-lopreiato** [comment]
Reviewed 28 of 28 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/636)*

**Comment by phil-lopreiato** [comment]
@nwalters512 merge conflicts

**Comment by phil-lopreiato** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/636)*

**Pull request merged**
