### PR TITLE
Elevate all the things!

### PR DESCRIPTION
**Pull request by nwalters512**
This adds elevation to all toolbars and tabs in the app to be more consistent with the material guidelines. As this uses the elevation APIs introduced with Lollipop, the elevation is only visible on 5.x+ devices. Also changes how the status bar color is set in activities with myTBA settings panels so that the status bar retains its transparency.

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Merge conflicts, but LGTM

**Comment by phil-lopreiato** [comment]
Travis error after merge: https://travis-ci.org/the-blue-alliance/the-blue-alliance-android/builds/64166411#L1684

Are all the resources added?

**Comment by nwalters512** [comment]
Yep, I just triple checked. Ughhhh.

**Comment by phil-lopreiato** [comment]
That's not even an error I've seen before :/

**Comment by nwalters512** [comment]
Huh... it passed!

**Comment by phil-lopreiato** [comment]
¯\_(ツ)_/¯

**Pull request merged**
