### PR TITLE
FAB layout fixes

### PR DESCRIPTION
**Pull request by nwalters512**
This should fix the weird FAB layout behavior we were seeing on 4.x devices. It turns out that if FABs are placed as a direct child of a CoordinatorLayout, the CL will translate the FAB to account for the extra padding that's added on 4.x devices to allow for the shadow. So, we still have to provide a margin for the FAB.

People with 4.x devices, please test this! I was able to test 2/3 activities with FABs, but not the myTBA settings activity that's launched from the myTBA fav/sub lists (I was running on an emulator where I couldn't enable myTBA).

### CODE REVIEW

**Comment by fangeugene** [comment]
FABs are disappearing for me. They show up (with proper margins now!) but then disappear a few seconds later.

**Comment by fangeugene** [comment]
Nevermind, the disappearing FAB issue was because myTBA was not enabled. Everything looks good.

**Comment by nwalters512** [comment]
That being said, we should probably fix this behavior for those of our users who choose not to enable myTBA. The FAB should be set to "invisible" in the layout file so it isn't rendered when the activity is launching. Then, we should show it with a nice scale animation once we're sure the user has myTBA enabled and should therefore see the FAB.

**Comment by fangeugene** [comment]
This is the first time I've seen the FAB show up and then disappear. I've had myTBA disabled before, and this didn't happen. Maybe it's because I'm running it on older hardware this time, assuming nothing in the code changed.

**Comment by nwalters512** [comment]
I noticed the same thing when I was running it in a 4.4 emulator, but I can't reproduce it on 5.1. It might be something different with how Android renders activities while launching? I'm not really sure. Either way, what I suggested should fix that in all cases. I'll try to take care of that tomorrow.

**Comment by phil-lopreiato** [comment]
@nwalters512 can you take this and #461 and put them up again against master?

**Comment by nwalters512** [comment]
I'll work on this a bit tonight. Still need people to investigate stuff on 4.x for me.

**Comment by phil-lopreiato** [comment]
Early next week, I'll flash my Nexus 5 back to KitKat and give you a hand with that

**Comment by Adam8234** [comment]
I have a few tablets running 4.4 KitKat. Do you want me to do testing
instead of flashing your device Phil?

On Sat, Oct 24, 2015 at 1:28 PM, Phil Lopreiato <notifications@github.com>
wrote:

> Early next week, I'll flash my Nexus 5 back to KitKat and give you a hand
> with that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/the-blue-alliance/the-blue-alliance-android/pull/474#issuecomment-150839667>
> .
>



-- 

Adam C
Programming Expert | FRC Krawler Developer | Team 2052 KnightKrawler

**Comment by phil-lopreiato** [comment]
If you can test, that'll be awesome!

**Comment by Adam8234** [comment]
What branch do you want me to pull?

**Comment by phil-lopreiato** [comment]
@nwalters512?

**Comment by phil-lopreiato** [comment]
Didn't see any issues here on my N5 on 4.4

**Pull request merged**
