### PR TITLE
Imgur media interface

### LINKED ISSUE #541: Team Media Suggestion Flow
App side component to https://github.com/the-blue-alliance/the-blue-alliance/issues/1362

## Backend Tasks
 - [ ] Update Cloud Endpoints to have a media suggestion url<sup>1</sup>. This will require some server side changes
 - [ ] Integrate Imgur API into app<sup>2</sup>
 - [ ] Make a background thread thing (probably IntentService?) to take image on device, upload to imgur<sup>3</sup>, and suggest to TBA. Use persistent notification for status updates. Be sure to handle lots of cases: TCP Timeout, imgur error, rate limit hit

## Frontend Tasks
 - [ ] Make a button to take a picture on Team or Team@Event page (do we want to be able to choose+upload existing picture?)
 - [ ] Prompt user for image title and description. Provide sane defaults.
 - [ ] Fire off above task

**<sup>1</sup> Cloud Endpoints Suggestion**
Needs to have:
 - User (done via oauth). Will need to have account signed in/myTBA enabled
 - Team Key
 - Year
 - Suggestion "kind" (media in this case)
 - Imgur url
 - Metadata (in this case, we want to pass `deletehash` up to the server so we can modify the image in the future, even though it was upload anonymously. And maybe some other stuff?)

**<sup>2</sup>Imgur API Things**
Docs: https://api.imgur.com/
Other Considerations:
 - Need to register app and get tokens
 - Note rate limiting (1,250 uploads per day or approximately 12,500 requests per day), remaining quota in `X-RateLimit-UserLimit` response header. 
 - [Image Upload Endpoint](https://api.imgur.com/endpoints/image#image-upload). Returns [basic response](https://api.imgur.com/models/basic).

Here is what the response looks like:
```
{
  "data": {
    "id": "rdwAFcH",
    "title": null,
    "description": null,
    "datetime": 1455648595,
    "type": "image\/jpeg",
    "animated": false,
    "width": 1200,
    "height": 675,
    "size": 784683,
    "views": 0,
    "bandwidth": 0,
    "vote": null,
    "favorite": false,
    "nsfw": null,
    "section": null,
    "account_url": null,
    "account_id": 0,
    "comment_preview": null,
    "deletehash": "BV0r1n6UoQayKlm",
    "name": "",
    "link": "http:\/\/i.imgur.com\/rdwAFcH.jpg"
  },
  "success": true,
  "status": 200
}
```

**<sup>3</sup>File Uploads With Retrofit**
https://github.com/square/retrofit/wiki/%5B1063%5D-How-to-upload-file---Retrofit---2.0

### PR DESCRIPTION
**Pull request by nwalters512**
DON'T MERGE YET.

This puts a frontend on Phil's Imgur uploading stuff.

Previews of the UI:

Imgur
Imgur

TODO
- [x] Use actual team number & year on preview screen
- [x] Hide FAB if user not logged into myTBA (they can't upload in that case)
- [x] Figure out why myTBA fab doesn't stay hidden (for users not logged into myTBA) when you swipe to another tab and back to the first tab in the team activity
- [x] Improve styling of preview screen?
- [ ] Stress-test the hell out of everything and try to break it (edge cases!)
- [x] Auto-gen title/description for Imgur upload
- [x] Display "hey, upload some images!" snackbar
 * May be in the form of a snackbar with a "more" button that launches a dialog with more info
- [ ] Once @fangeugene updates the verbiage on the site to reflect that team images should be robot-centric, integrate that verbiage into the upload flow sometime
 * Should probably be a dialog with a "do not show again" checkbox, and also a "help" (question mark) menu item in the confirm suggestion activity so that users can see it again if needed

Closes #541

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/609)

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Really nicely done!

The only thing I'd like to see added is a popup on the main team view that nudged people to suggest images (people won't use it if they don't know the feature exists).

Maybe the first 5 times they open ViewTeamActivity, we can show a popup using the mytba update status snackbar saying "You can now submit robot images directly from the Media tab!" or something

**Comment by fangeugene** [comment]
Really slick. "Confirm Suggestion" seems really close to the edge of the screen.

**Comment by nwalters512** [comment]
Yeah, there's something weird going on with the content inset. I've been meaning to figure that out.

**Comment by phil-lopreiato** [comment]
Can you account for #610 in this pull? This is what will end up updating the support lib, so let's pin it at the source.

**Comment by nwalters512** [comment]
Yeah. I'll let you test it when I've followed the advice from SO to make sure it worked.

**Comment by nwalters512** [comment]
The app now launches fine on my KitKat emulator. Should be fixed.

**Comment by nwalters512** [comment]
Current iteration of the UI:

Imgur

**Comment by fangeugene** [comment]
Nice. The yellow and red look a bit tacky imo. Can we do plain white buttons?

**Comment by nwalters512** [comment]
I could see making cancel white, but I want to keep confirm a little more colorful to accentuate it. Sort of like the "confirm" view of the Google Camera app, similar to below. Do you like the yellow fab, or should I use a different color?

Google camera screenshot

**Comment by fangeugene** [comment]
Yellow/white sounds good. I'm just worried the UI will look like skittles with too many colors =)

**Comment by nwalters512** [comment]
It's not like primary colors scream "childish" or anything!

**Comment by nwalters512** [comment]
Good call on the white. Much better.

Imgur

**Comment by nwalters512** [comment]
Snackbar is complete. It will show persistently on each ViewTeamActivity startup until the user deliberately dismisses it.

Imgur

**Comment by phil-lopreiato** [comment]
:lgtm:
Just fix up that minor wakelock thing, I want to be extra cautious there

---

Reviewed 27 of 40 files at r1, 4 of 8 files at r2, 14 of 16 files at r3, 3 of 3 files at r4, 1 of 2 files at r5, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurSuggestionService.java, line 183 \[r6\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/609#-KCN0SCPKxL0S4J0ttpz:-KCN0LUSRu2UHXO5rMY4:1444097358) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/5dc302784af70c4464d6a254087b6fc13b9b9d50/android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurSuggestionService.java#L183)):*
Move this into the `try`

---

*[android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurSuggestionService.java, line 192 \[r6\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/609#-KCN0V-iKsbbLXU5HTA2:-KCN0V-j8Ov88w5JPlsh:-472263399) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/5dc302784af70c4464d6a254087b6fc13b9b9d50/android/src/main/java/com/thebluealliance/androidclient/imgur/ImgurSuggestionService.java#L192)):*
Put this in a `finally`.  We don't want to mess around with wakelocks and have them sap battery life.

---

*[android/src/main/java/com/thebluealliance/androidclient/listeners/TeamClickListener.java, line 63 \[r6\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/609#-KCN1DWV_86_qu-ZGPLg:-KCN1DWWTBarENgS9nJB:379191625) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/5dc302784af70c4464d6a254087b6fc13b9b9d50/android/src/main/java/com/thebluealliance/androidclient/listeners/TeamClickListener.java#L63)):*
Surprised we hadn't done this one before...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/609#-:-KCMyzTOCK0xiQ6IYJpp:-323564752)*

**Comment by phil-lopreiato** [comment]
I can also confirm that this works on my N5 running KitKat, so we're good to go
:shipit:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/609#-:-KCN4W7qMv_jWK_w8hmO:1385654704)*

**Pull request merged**
