### PR TITLE
Changes to the Firebase ticker

### PR DESCRIPTION
**Pull request by nwalters512**
This improves the ticker experience across the app

* Ticker is decoupled from GamedayActivity
* Ticker appears as a tab in individual events
* Filtering is now done with a bottom button bar, instead of a FAB
* Ticker uses the NoDataView to warn of an empty ticker, Firebase error, no items matching filter, etc.

Screenshots of the new visual look:

Imgur

Imgur

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/540)

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Looks good!

Do you think the filter bar at the bottom should be the secondary color instead of white (If you tried it and it looks horrible, no worries).

And the default tab stays at info, right?

**Comment by nwalters512** [comment]
I didn't try making it the secondary color. I could give it a shot, but instinct says it would be too much!

Default tab is still info, yes.

**Comment by nwalters512** [comment]
I would like to test this with real-time Firebase info, mostly to make sure that state transitions from no data->data work correctly. Couldn't think of a good way to test this though. Any thoughts?

**Comment by fangeugene** [comment]
Create a test Firebase account?

**Comment by phil-lopreiato** [comment]
You're going to have to update the urls to be consistent with https://github.com/the-blue-alliance/the-blue-alliance/commit/ff669d465cbfb28dc2d646fb76b13852daa4ee0c and https://github.com/the-blue-alliance/the-blue-alliance/commit/1f950dce007c38208e49b55d980eb63406d890b3

**Comment by phil-lopreiato** [comment]
And I put a crap ton of notifications at https://intense-fire-9780.firebaseio.com/events/2015cthar/notifications.json

**Comment by phil-lopreiato** [comment]
@nwalters512 did you test this/are you happy?

Also, this connects to #487

**Comment by phil-lopreiato** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java, line 90 \[r2\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/540#-KAg-4SyobPbp9SJudeZ:-KAg-4SyobPbp9SJude_:1789427200) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/fc62927b0f0771e025f3b3869a966a856a1cb1e7/android/src/main/java/com/thebluealliance/androidclient/fragments/FirebaseTickerFragment.java#L90)):*
Don't need this print

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/540)*

**Comment by phil-lopreiato** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/540)*

**Pull request merged**
