### PR TITLE
Notification improvements

### LINKED ISSUE #557: Recent Notifications doesn't play nicely with live incoming notifications
If you get a few notifications in the background and then open Recent Notifications, everything works as expected. However, if you're in the activity and a new notification comes in, you're left with a disappointing and useless "summary" card for the new notification. Quitting and restarting the activity makes everything render nicely again.

Screenshot  of issue

### PR DESCRIPTION
**Pull request by nwalters512**
A lot of changes and improvements to notifications.

* the Recent Notifications list now properly renders incoming notifications in real time
* changes to how notifications are marked as "not active" when tapped or dismissed
* proper rendering for broadcast notifications in recent notifications
* removed RecentNotificationsActivity in favor of RecentNotificationsFragment in HomeActivity
* other small stuff that I now forget

Fixes #557

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/561)

### CODE REVIEW

**Comment by nwalters512** [comment]
It would be nice to get test coverage for notifications eventually, but if we're trying to get #557 done by tonight, I've tested this stuff extensively by hand, and it should be ready to ship.

**Comment by phil-lopreiato** [comment]
Fix existing tests?

**Comment by nwalters512** [comment]
I'm on it. Forgot to run the test suite locally :)

**Comment by phil-lopreiato** [comment]
Reviewed 19 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/561)*

**Pull request merged**
