### PR TITLE
Subscriber Bugfix: Clear data to bind after check

### LINKED ISSUE #551: Issues Opening 2016 Matches
Appears, then disappears. Seems like issues from matches in db

### PR DESCRIPTION
**Pull request by phil-lopreiato**
If the first time it executes goes successfully and we generate some
data to bind, but the second time has some error (like the server side
erroring), keep the old data. Only clear when we know we have something
to replace it with

Fixes #551

[Review on Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/554)

### CODE REVIEW

**Comment by nwalters512** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/554)*

**Comment by nwalters512** [comment]
LGTM.

All this duplicate code makes me think it would be nice to build this behavior into the base `Subscriber` class instead of having to duplicate the behavior in every single subclass. But you know the data framework better than me, I'm not sure if that's possible.

**Comment by phil-lopreiato** [comment]
We do have `BaseAPISubscriber`, which I tried first, but there was an issue.

Some Subscribers have a custom model (e.g. a wrapper object for a `Match` and an `Event`, say). We only want to run the subscriber when all components are non-null, which we can't test in the superclass because we don't know the types.

The appropriate way to fix this is to allow Subscribers to override a "isDataValid" method or something where they can do all the tests they need (and default to a null check). 

Hmmm, that actually sounds better...

**Comment by nwalters512** [comment]
Nice work, it looks a lot cleaner this way

**Pull request merged**
