### PR TITLE
Show Playoff Advancement for Alliances

### LINKED ISSUE #653: Show Result in Event Alliances View
Next to each alliance, show how far they made it in playoffs (QF, SF, F, W)

### PR DESCRIPTION
**Pull request by phil-lopreiato**
device-2016-04-06-215355

Closes #653

---
This change is [Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/668)

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Works for octofinals too!
device-2016-04-06-224410

**Comment by nwalters512** [comment]
Thought for an enhancement: have a dialog explaining what the letters indicate when you click on them? You and I know what they mean, but I could see my parents being like "wat".

**Comment by phil-lopreiato** [comment]
> Thought for an enhancement: have a dialog explaining what the letters indicate when you click on them? You and I know what they mean, but I could see my parents being like "wat". 

Make this a new issue? It's on the table for next week, I'm running out of time for tonight

**Comment by 1fish2** [comment]
Terrific!

Suggestion: Keep the **Alliance \#n:** column leftmost since it contains the row titles.

**Pull request merged**
