### PR TITLE
Revamped info pages

### PR DESCRIPTION
**Pull request by nwalters512**
!!!DO NOT MERGE!!!

Revamps the team/event info pages to utilize a list of cards similar to the one found in the stock contacts app. So far I've only done this for teams, but I'll be doing events next. I'll keep this PR updated with my progress.

Screenshots:

Imgur

Imgur

### CODE REVIEW

**Comment by nwalters512** [comment]
This is ready for review!

**Comment by fangeugene** [comment]
I miss the four color social media bar

**Comment by nwalters512** [comment]
Hmm. I could recolor the icons?

**Comment by phil-lopreiato** [comment]
I kinda miss the bar too, maybe some more color will help.

**Comment by gregmarra** [comment]
I personally prefer this to the icon bar – I don't think it was obvious that those were buttons and they felt different from the rest of the visual style of the app.

Is this pull request good to go otherwise? We should bias towards improvements and keep iterating on design through the fall.

**Comment by nwalters512** [comment]
Design-wise, this is ready to go. We'll have to do some work to merge it with the work being done on the datafeed, but that shouldn't be too complex

**Comment by nwalters512** [comment]
I'm going to close this and open a new pull request that targets the datafeed-v3 branch.

**Pull request closed without merging**
