### PR TITLE
Enable Checkstyle Code Analysis

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Summary: Make sure we have some base code style guidelines!

Test Plan: CI passes

---
This change is [Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/745)

### CODE REVIEW

**Comment by nwalters512** [comment]
Looks like making `Database` final breaks unit tests.

**Comment by 1fish2** [comment]
Suggestion: Split this into a PR that brings the code into conformance and
a small PR that adds Checkstyle to the build and CI.

**Comment by phil-lopreiato** [comment]
Yeah, I can rebase the commits around (probably a better idea)

**Comment by phil-lopreiato** [comment]
Actually, I think I'll just merge this one without squashing (it isn't a clean rebase). Shouldn't have assumed git would cooperate :stuck_out_tongue:

**Pull request merged**
