### PR TITLE
Render events using RecyclerView

### PR DESCRIPTION
**Pull request by nwalters512**
List item click testing for the relevant fragments is currently disabled; I couldn't figure out how to use Robolectric to test `RecyclerView`s. @phil-lopreiato want to take a look?

---
This change is [Reviewable](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance-android/697)

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Robolectric is a little screwy sometimes, I'll take a look though. 

I'm thinking it'll be better to run full instrumentation tests with the new (faster) emulator than deal with robolectric and memory issues. But that's a summer project...

**Comment by nwalters512** [comment]
Agreed. If that's the consensus, I'm fine with leaving the tests disabled for the time being, they aren't critical.

**Comment by phil-lopreiato** [comment]
Yeah, I'm fine with leaving them disabled for now, as well

**Comment by phil-lopreiato** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java, line 210 \[r1\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697#-KFjgtA_ywf0Op1cT64s:-KFjgtAag2cpgieTnyux:1585833001) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/f6487e248bd6cee547032eb92a8939c72cc58e0e/android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java#L210)):*
Why is this being removed?

---

*[android/src/main/java/com/thebluealliance/androidclient/models/Event.java, line 469 \[r1\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697#-KFjg7NVgt4mMCUtXQ4S:-KFjg7NVgt4mMCUtXQ4T:-1688049818) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/e9e54fe72df58812f9761a5091c57b72a923dfa3/android/src/main/java/com/thebluealliance/androidclient/models/Event.java#L469)):*
Rendering coded should be in `EventRenderer`, not in the model. Is there a reason you put it here? I don't like the model classes doing that much, and rendering is a discrete function that we can keep separate.

---

*[android/src/main/res/layout/list_item_event.xml, line 6 \[r1\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697#-KFjgcoRUFEkep4sse1Y:-KFjgcoRUFEkep4sse1Z:-128704716) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/e9e54fe72df58812f9761a5091c57b72a923dfa3/android/src/main/res/layout/list_item_event.xml#L6)):*
Did you test to make sure clicking still worked? I think adding this is what broke the team@event clicking earlier in the season

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697)*

**Comment by nwalters512** [comment]
*[android/src/main/java/com/thebluealliance/androidclient/models/Event.java, line 469 \[r1\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697#-KFjg7NVgt4mMCUtXQ4S:-KFjqt77rg70U7PCamBP:582023490) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/e9e54fe72df58812f9761a5091c57b72a923dfa3/android/src/main/java/com/thebluealliance/androidclient/models/Event.java#L469)):*
Back when I was first architecting all the recyclerview stuff, we discussed how rendering should happen. After weighing the merits of having models render themselves vs having a separate component convert models to viewmodels, we decided that having models be in charge of that process was the best way to go. I forget the reasoning for that though. If you'd rather move all model->viewmodel code to external classes, I can redesign everything. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697)*

**Comment by phil-lopreiato** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[android/src/main/java/com/thebluealliance/androidclient/models/Event.java, line 469 \[r1\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697#-KFjg7NVgt4mMCUtXQ4S:-KFjsKtfTCQ0CiXDSjJa:-1589433591) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/e9e54fe72df58812f9761a5091c57b72a923dfa3/android/src/main/java/com/thebluealliance/androidclient/models/Event.java#L469)):*
Oh, you're right, I forgot we discussed that already. And I guess creating a ViewModel isn't that bad. If it gets unwieldy in the future, we can refacator it then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697)*

**Comment by nwalters512** [comment]
*[android/src/main/res/layout/list_item_event.xml, line 6 \[r1\]](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697#-KFjgcoRUFEkep4sse1Y:-KFjw4zl4x1DzHD7kyHo:-2096039412) ([raw file](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/e9e54fe72df58812f9761a5091c57b72a923dfa3/android/src/main/res/layout/list_item_event.xml#L6)):*
I did test clicking, it's working normally as far as I can tell.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/the-blue-alliance/the-blue-alliance-android/697)*

**Pull request merged**
