### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by nwalters512**
General cleanup of the project, including:

* removed unused resources
* moved more strings into resource files
* fixed minor styling issues
* refactored class/package names
* bumps libraries and such to their latest versions
* removed redundant/useless code and simplified other code

### CODE REVIEW

**Comment by nwalters512** [comment]
#420mergeit

Not sure why the travis build is failing. It looks like retrolambda is failing, but it builds just fine on my machine. I'll investigate.

**Comment by phil-lopreiato** [comment]
It fails to compile if I check it out, also

**Comment by phil-lopreiato** [comment]
Here's a debug output with the compile errors

http://pastebin.com/c46SPjUU

**Comment by nwalters512** [comment]
That looks unrelated to the Travis error. Looks like the tests can't import any of our code for some reason. Tests aren't my area of expertise, does someone else want to take a look?

**Comment by phil-lopreiato** [comment]
That's what I got after a fresh checkout and even running gradlew build. It didn't even get to the tests process. I can take a closer look tomorrow though

**Comment by nwalters512** [comment]
Success! Turns out the issue was with bumping the support library version: https://github.com/evant/gradle-retrolambda/issues/95

**Comment by phil-lopreiato** [comment]
Nice find! Odd error...

Anyway, #shipit

**Pull request merged**
